services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env_app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    env_file:
      - .env_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    ports:
      - "6379:6379"